/**
 * Token YAML emitter.
 *
 * Turns the full design-token definitions (from the resolvers) into the clean
 * YAML data files the design-system website consumes — one file per token type,
 * under `tokens/<platform>/`. This module owns the YAML *shape*; the definition
 * readers own where the tokens come from.
 *
 * Builders are pure (definitions → plain objects) so they're easy to test;
 * `writeTokenFile` is the only part that touches the filesystem.
 */

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

/**
 * Build the `colours.yaml` data shape: a list of groups, each with an optional
 * heading/description and its colours. Without a grouping config every colour
 * lands in a single untitled group (grouping arrives in a later step), so the
 * output is always valid and complete.
 *
 * @param {{token:string, light?:string, dark?:string}[]} definitions
 * @returns {{groups: {heading?:string, description?:string, colours:object[]}[]}}
 */
function buildColourGroups(definitions) {
  return { groups: [{ colours: definitions.map(toColour) }] };
}

/** One colour entry: token name plus lower-cased light/dark hex (dark omitted when absent). */
function toColour(def) {
  const out = { token: def.token };
  if (def.light) out.light = lowerHex(def.light);
  if (def.dark) out.dark = lowerHex(def.dark);
  return out;
}

function lowerHex(hex) {
  return typeof hex === "string" ? hex.toLowerCase() : hex;
}

/**
 * Serialise a token data object to YAML, with a banner noting it's generated.
 * Double-quoted scalars match the sample's `"#005eb8"` style, and unbounded
 * line width keeps each entry on its own line.
 */
function dumpYaml(data, { platform, category } = {}) {
  const body = yaml.dump(data, {
    lineWidth: -1,
    quotingType: '"',
    noRefs: true,
  });
  const banner =
    platform && category
      ? `# ${category} tokens for ${platform} — generated by Fractionator. Do not edit by hand.\n`
      : "# Generated by Fractionator. Do not edit by hand.\n";
  return banner + body;
}

/**
 * Write one token file to `<outputDir>/tokens/<platform>/<name>.yaml`.
 *
 * @returns {string} the path written
 */
function writeTokenFile(outputDir, platform, name, data) {
  const dir = path.join(outputDir, "tokens", platform);
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `${name}.yaml`);
  fs.writeFileSync(
    filePath,
    dumpYaml(data, { platform, category: name }),
  );
  return filePath;
}

module.exports = {
  buildColourGroups,
  dumpYaml,
  writeTokenFile,
};
