const { test } = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const yaml = require("js-yaml");
const {
  buildColourGroups,
  buildTypeSizes,
  buildSpacing,
  dumpYaml,
  writeTokenFile,
} = require("./token-emitter");

test("buildColourGroups puts every colour in one default group, lower-casing hex", () => {
  const defs = [
    { token: "nhsBlue", light: "#005EB8", dark: "#52A0FF" },
    { token: "nhsWarmYellow", light: "#FFB81C" },
  ];
  assert.deepStrictEqual(buildColourGroups(defs), {
    groups: [
      {
        colours: [
          { token: "nhsBlue", light: "#005eb8", dark: "#52a0ff" },
          { token: "nhsWarmYellow", light: "#ffb81c" }, // no dark key
        ],
      },
    ],
  });
});

test("buildColourGroups yields an empty group for no definitions", () => {
  assert.deepStrictEqual(buildColourGroups([]), { groups: [{ colours: [] }] });
});

test("buildColourGroups places colours by spec, in spec order, with description", () => {
  const defs = [
    { token: "nhsBlue", light: "#005EB8", dark: "#52A0FF" },
    { token: "nhsGreen", light: "#007F3B" },
    { token: "nhsAccentColor", light: "#005EB8", dark: "#52A0FF" },
  ];
  const spec = [
    {
      heading: "Accent colour",
      description: "The tint colour.",
      tokens: ["nhsAccentColor"],
    },
    { heading: "Core palette", tokens: ["nhsGreen", "nhsBlue"] },
  ];
  assert.deepStrictEqual(buildColourGroups(defs, spec), {
    groups: [
      {
        heading: "Accent colour",
        description: "The tint colour.",
        colours: [{ token: "nhsAccentColor", light: "#005eb8", dark: "#52a0ff" }],
      },
      {
        heading: "Core palette",
        colours: [
          { token: "nhsGreen", light: "#007f3b" },
          { token: "nhsBlue", light: "#005eb8", dark: "#52a0ff" },
        ],
      },
    ],
  });
});

test("buildColourGroups sweeps unplaced colours into a trailing Other group", () => {
  const defs = [
    { token: "nhsBlue", light: "#005EB8" },
    { token: "nhsStray", light: "#123456" },
  ];
  const spec = [{ heading: "Core palette", tokens: ["nhsBlue"] }];
  assert.deepStrictEqual(buildColourGroups(defs, spec), {
    groups: [
      { heading: "Core palette", colours: [{ token: "nhsBlue", light: "#005eb8" }] },
      { heading: "Other", colours: [{ token: "nhsStray", light: "#123456" }] },
    ],
  });
});

test("buildColourGroups skips spec tokens with no matching definition and omits empty Other", () => {
  const defs = [{ token: "nhsBlue", light: "#005EB8" }];
  const spec = [{ heading: "Core palette", tokens: ["nhsBlue", "nhsGhost"] }];
  assert.deepStrictEqual(buildColourGroups(defs, spec), {
    groups: [
      { heading: "Core palette", colours: [{ token: "nhsBlue", light: "#005eb8" }] },
    ],
  });
});

test("buildTypeSizes names semantic roles and synthesises size tokens", () => {
  const typography = [
    { key: "caption2", kind: "semantic", size: 11, weight: null },
    { key: "sp-16", kind: "explicit", size: 16, weight: null },
    { key: "system-40-bold", kind: "explicit", size: 40, weight: "bold" },
    { key: "displayLarge", kind: "semantic", size: null, weight: null },
  ];
  assert.deepStrictEqual(buildTypeSizes(typography), {
    sizes: [
      { token: "caption2", size: 11 },
      { token: "size-16", size: 16 },
      { token: "size-40-bold", size: 40, weight: "bold" },
      { token: "displayLarge" }, // unresolved size → no size key
    ],
  });
});

test("buildSpacing synthesises spacing-N tokens with units", () => {
  const spacing = [
    { value: 4, unit: "dp" },
    { value: 16, unit: "dp" },
    { value: 7.5, unit: "pt" },
  ];
  assert.deepStrictEqual(buildSpacing(spacing), {
    spacing: [
      { token: "spacing-4", value: 4, unit: "dp" },
      { token: "spacing-16", value: 16, unit: "dp" },
      { token: "spacing-7.5", value: 7.5, unit: "pt" },
    ],
  });
});

test("dumpYaml round-trips and quotes hex values", () => {
  const data = buildColourGroups([{ token: "nhsBlue", light: "#005EB8" }]);
  const text = dumpYaml(data, { platform: "ios", category: "colours" });

  assert.match(text, /^# colours tokens for ios — generated by Fractionator/);
  // Hex starts with '#', so it must be quoted to avoid being read as a comment.
  assert.match(text, /light: "#005eb8"/);
  // The banner is a YAML comment, so the document still parses to the data.
  assert.deepStrictEqual(yaml.load(text), {
    groups: [{ colours: [{ token: "nhsBlue", light: "#005eb8" }] }],
  });
});

test("writeTokenFile writes to tokens/<platform>/<name>.yaml", () => {
  const outputDir = fs.mkdtempSync(path.join(os.tmpdir(), "fract-tokens-"));
  try {
    const data = buildColourGroups([{ token: "blue", light: "#005EB8" }]);
    const written = writeTokenFile(outputDir, "android", "colours", data);

    assert.strictEqual(
      written,
      path.join(outputDir, "tokens", "android", "colours.yaml"),
    );
    assert.deepStrictEqual(yaml.load(fs.readFileSync(written, "utf-8")), {
      groups: [{ colours: [{ token: "blue", light: "#005eb8" }] }],
    });
  } finally {
    fs.rmSync(outputDir, { recursive: true, force: true });
  }
});
