/**
 * Token YAML emitter.
 *
 * Turns the full design-token definitions (from the resolvers) into the clean
 * YAML data files the design-system website consumes — one file per token type,
 * under `tokens/<platform>/`. This module owns the YAML *shape*; the definition
 * readers own where the tokens come from.
 *
 * Builders are pure (definitions → plain objects) so they're easy to test;
 * `writeTokenFile` is the only part that touches the filesystem.
 */

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

/**
 * Build the `colours.yaml` data shape: a list of groups, each with an optional
 * heading/description and its colours.
 *
 * With no grouping spec, every colour lands in a single untitled group, so the
 * output is always valid and complete. With a spec (a list of
 * `{heading, description?, tokens}` group defs, from the grouping config), each
 * colour is placed by token name into its group, in the order the spec lists
 * them; any defined colour the spec doesn't place falls into a trailing `Other`
 * group so nothing is silently dropped and gaps in the config are visible.
 *
 * @param {{token:string, light?:string, dark?:string}[]} definitions
 * @param {{heading:string, description?:string, tokens:string[]}[]} [spec]
 * @returns {{groups: {heading?:string, description?:string, colours:object[]}[]}}
 */
function buildColourGroups(definitions, spec) {
  if (!spec || spec.length === 0) {
    return { groups: [{ colours: definitions.map(toColour) }] };
  }

  const byToken = new Map(definitions.map((d) => [d.token, d]));
  const assigned = new Set();
  const groups = [];

  for (const def of spec) {
    const group = { heading: def.heading };
    if (def.description) group.description = def.description;
    group.colours = [];
    for (const token of def.tokens || []) {
      const colour = byToken.get(token);
      if (!colour || assigned.has(token)) continue;
      assigned.add(token);
      group.colours.push(toColour(colour));
    }
    groups.push(group);
  }

  // Trailing catch-all for any defined colour the spec didn't place.
  const leftover = definitions.filter((d) => !assigned.has(d.token));
  if (leftover.length > 0) {
    groups.push({ heading: "Other", colours: leftover.map(toColour) });
  }

  return { groups };
}

/** One colour entry: token name plus lower-cased light/dark hex (dark omitted when absent). */
function toColour(def) {
  const out = { token: def.token };
  if (def.light) out.light = lowerHex(def.light);
  if (def.dark) out.dark = lowerHex(def.dark);
  return out;
}

function lowerHex(hex) {
  return typeof hex === "string" ? hex.toLowerCase() : hex;
}

/**
 * Serialise a token data object to YAML, with a banner noting it's generated.
 * Double-quoted scalars match the sample's `"#005eb8"` style, and unbounded
 * line width keeps each entry on its own line.
 */
function dumpYaml(data, { platform, category } = {}) {
  const body = yaml.dump(data, {
    lineWidth: -1,
    quotingType: '"',
    noRefs: true,
  });
  const banner =
    platform && category
      ? `# ${category} tokens for ${platform} — generated by Fractionator. Do not edit by hand.\n`
      : "# Generated by Fractionator. Do not edit by hand.\n";
  return banner + body;
}

/**
 * Write one token file to `<outputDir>/tokens/<platform>/<name>.yaml`.
 *
 * @returns {string} the path written
 */
function writeTokenFile(outputDir, platform, name, data) {
  const dir = path.join(outputDir, "tokens", platform);
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `${name}.yaml`);
  fs.writeFileSync(
    filePath,
    dumpYaml(data, { platform, category: name }),
  );
  return filePath;
}

module.exports = {
  buildColourGroups,
  dumpYaml,
  writeTokenFile,
};
